Feature/java7 compliance
SmarterApp/TDS_Common pull request #6
Opened 2016-11-11 16:21 UTC by millerts

Adds Joda time conversion in addition to Java 8

2016-11-11 19:18 UTC, jeffjohnson9046 approved these changes

2016-11-11 20:42 UTC, jtreuting requested changes

2016-11-11 20:42 UTC, jtreuting commented on src/main/java/tds/common/data/mapping/ResultSetMapperUtility.java
> +    public static Timestamp mapInstantToTimestamp(org.joda.time.Instant time) {
Isn't this one the joda time version, so shouldn't it be named `mapJodaInstantToTimestamp`

2016-11-11 20:42 UTC, jtreuting commented on src/main/java/tds/common/data/mapping/ResultSetMapperUtility.java
> +    public static org.joda.time.Instant mapTimeStampToJodaInstant(ResultSet rs, String columnLabel) throws SQLException {
Casing of TimeStamp is inconsistent between methods.  I would vote for Timestamp instead of TimeStamp since that is the casing of the java object.

2016-11-16 16:50 UTC, millerts commented on src/main/java/tds/common/data/mapping/ResultSetMapperUtility.java
> +    public static org.joda.time.Instant mapTimeStampToJodaInstant(ResultSet rs, String columnLabel) throws SQLException {
Changed.

2016-11-16 17:04 UTC, merged